version: "3"
services:
  postgres:
    build: postgres
  devopsstats:
    environment:
      - EXTERNAL_KUBE=yes
      - DEVOPSSTATS_DATABASE_URL=jdbc:postgresql://postgres/devopsstatsdb?user=devopsstatsdbuser&password=xxxxpasswd
      - SENTRY_DSN=http://a-sentry-key:a-sentry-secret@wiremock-proxy:8080/sentry/213123
      - GITHUB_TOKEN=replaceme
      - TRAVIS_CI_TOKEN=replaceme
      - SEMAPHORE_CI_TOKEN=replaceme
      - GITHUB_ORG=dlebrero
  wiremock-proxy:
    image: rodolpheche/wiremock:2.16.0-alpine
    volumes:
      - ./wiremock:/etc/wiremock/files
    command: --root-dir /etc/wiremock/files --no-request-journal --verbose