apiVersion: v1
kind: Service
metadata:
  name: akvo-devopsstats
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    run: akvo-devopsstats
